version: 2

before:
  hooks:
  - grep -q "version = \"{{ .Version }}\"" Cargo.toml

universal_binaries:
  - replace: true

builds:
  - builder: rust
    tool: cross
    command: build
    flags:
      - --release
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    output: true
    artifacts: checksum

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    maintainer: k4i6 <info@k4i.ch>
    formats:
      - deb
      - apk
      - rpm

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  replace_existing_draft: true

homebrew_casks:
  - repository:
      owner: rexpose
      name: homebrew-tap
    directory: Casks
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rexpose"]
          end

winget:
  - publisher: k4i6 <info@k4i.ch>
    package_identifier: rexpose.rexpose
    short_description: A reverse proxy to expose TCP and UDP services behind any NAT via a public server.
    license: "mit"
    repository:
      owner: rexpose
      name: winget-pkgs
      pull_request:
        enabled: true
        base:
            owner: microsoft
            name: winget-pkgs
            branch: master